package edu.gatech.hackgt.budslist.models;

public enum Department {
    ACCT,AE,AS,APPH,ASE,ARBC,ARCH,BIOL,BMEJ,BMED,BMEM,BC,BCP,CETL,CHBE,CHEM,CHIN,CP,CEE,COA,COE,
    COS,CX,CSE,CS,COOP,UCGA,EAS,ECON,ECEP,ECE,ENGL,FS,FREE,FREN,GT, GTL,GRMN,HP,HS,HIN,HIST,HTS,
    HUM,ID,ISYE,INTA,IL,INTN,IMBA,IPCO,IPFS,IPIN,IPSA,IAC,JAPN,KOR,LATN,LS,LING,LCC,LMC,MGT,MOT,
    MLDR,MSE,MATH,ME,MP,MSL,ML,MUSI,NS,NEUR,NRE,PERS,PHIL,PHYS,POL,PTFE,DOPP,PSYC,PUBJ,PUBP,RUSS,
    SCI,SLS,SS,SOC,SPAN
}
